version: '2'

services:
  jsonkeeper:
    build: ./JSONkeeper
    ports:
      - '9001:8000'
    volumes:
      - ./JSONkeeper/config.ini:/jsonkeeper/config.ini

  canvasindexer:
    build: ./Canvas-Indexer
    ports:
      #  - '9002:8000' # This is the setting when the service is running under gunicorn.
      #  It is failing with a proxy error for now, but I don't know why.
      #  Setting this to 9002:80 doesn't help, even if the service is not running under gunicorn.
      - '9002:8000'
    volumes:
      - ./Canvas-Indexer/config.ini:/canvasindexer/config.ini
      - ./Canvas-Indexer/log.txt:/canvasindexer/log.txt

  curationfinder:
    build: ./IIIFCurationFinder
    ports:
      - '9004:80'

  curationviewer:
    build: ./IIIFCurationViewer
    ports:
      - '9003:80'

  curationmanager:
    build: ./IIIFCurationManager
    ports:
      - '9005:80'

  curationeditor:
    build: ./IIIFCurationEditor
    ports:
      - '9006:80'

#  loris:
#    image: 'lorisimageserver/loris'
#    ports:
#      - '9007:5004'
#    volumes:
#      - ./loris/images:/opt/loris/tests/img
